<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Hira_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get hira by no
     */
    function get_hira($no)
    {
        return $this->db->get_where('hira',array('no'=>$no))->row_array();
    }
        
    /*
     * Get all hira
     */


    function get_all_sp3()
    {
        $this->db->order_by('no_sp3', 'desc');
        return $this->db->get('sp3')->result_array();
    }
        

    function get_all_hira()
    {
        $this->db->order_by('no', 'desc');
        return $this->db->get('hira')->result_array();
    }
        
    /*
     * function to add new hira
     */
    function add_hira($params)
    {
        $params['no']  = $this->new_no();
        $this->db->insert('hira',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update hira
     */
    function update_hira($no,$params)
    {
        $this->db->where('no',$no);
        return $this->db->update('hira',$params);
    }
    
    /*
     * function to delete hira
     */
    function delete_hira($no)
    {
        return $this->db->delete('hira',array('no'=>$no));
    }

    function new_no(){
        $q = $this->db->from('hira')->order_by('no','desc')->get()->row();
        if (empty($q)){
            return 1;
        }else{
            return $q->no + 1;  
        }
    }
}
