<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ikd_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ikd by no
     */
    function get_ikd($no)
    {
        return $this->db->get_where('ikd',array('no'=>$no))->row_array();
    }
        
    /*
     * Get all ikd
     */
    function get_all_ikd()
    {
        $this->db->order_by('no', 'desc');
        return $this->db->get('ikd')->result_array();
    }
        
    /*
     * function to add new ikd
     */
    function add_ikd($params)
    {
        $params['no'] = $this->generate_id();
        $this->db->insert('ikd',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ikd
     */
    function update_ikd($no,$params)
    {
        $this->db->where('no',$no);
        return $this->db->update('ikd',$params);
    }
    
    /*
     * function to delete ikd
     */
    function delete_ikd($no)
    {
        return $this->db->delete('ikd',array('no'=>$no));
    }

    public function generate_id(){
        $tabel = 'ikd';
        $kolom = 'no';
        $lebar = 7;
        $awalan = 'IKD-EJA';
        if(empty($awalan)){
            $query="select $kolom from $tabel order by $kolom desc limit 1";
        }else{
            $query="select $kolom from $tabel where $kolom like '%$awalan%' order by $kolom desc limit 1";
        }
        $hasil          = $this->db->query($query)->row();
        $jumlahrecord   = count($hasil);
        if($jumlahrecord == 0)
            $nomor=1;
        else
        {
            $row=$hasil;
            $nomor=intval(substr($row->$kolom,strlen($awalan)))+1;
        }
        if($lebar>0){
            $angka = $awalan.str_pad($nomor,$lebar,"0",STR_PAD_LEFT);
        }else{
            $angka = $awalan.$nomor;
        }
            
        return $angka;
    }
}
