<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ikp_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ikp by no
     */
    function get_ikp($no)
    {
        return $this->db->get_where('ikp',array('no'=>$no))->row_array();
    }
        
    /*
     * Get all ikp
     */
    function get_all_ikp()
    {
        $this->db->order_by('no', 'desc');
        return $this->db->get('ikp')->result_array();
    }
        
    /*
     * function to add new ikp
     */
    function add_ikp($params)
    {
        $params['no'] = $this->generate_id();
        $this->db->insert('ikp',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ikp
     */
    function update_ikp($no,$params)
    {
        $this->db->where('no',$no);
        return $this->db->update('ikp',$params);
    }
    
    /*
     * function to delete ikp
     */
    function delete_ikp($no)
    {
        return $this->db->delete('ikp',array('no'=>$no));
    }
    public function generate_id(){
        $tabel = 'ikp';
        $kolom = 'no';
        $lebar = 7;
        $awalan = 'IKP-EJA';
        if(empty($awalan)){
            $query="select $kolom from $tabel order by $kolom desc limit 1";
        }else{
            $query="select $kolom from $tabel where $kolom like '%$awalan%' order by $kolom desc limit 1";
        }
        $hasil          = $this->db->query($query)->row();
        $jumlahrecord   = count($hasil);
        if($jumlahrecord == 0)
            $nomor=1;
        else
        {
            $row=$hasil;
            $nomor=intval(substr($row->$kolom,strlen($awalan)))+1;
        }
        if($lebar>0){
            $angka = $awalan.str_pad($nomor,$lebar,"0",STR_PAD_LEFT);
        }else{
            $angka = $awalan.$nomor;
        }
            
        return $angka;
    }
}
